myRDB/urls.py
from django.conf.urls import url
from django.urls import path, include

from . import views

app_name = 'myRDB'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.IndexView.as_view(), name='index'),
    path('profile/compare/', views.Compare.as_view(), name='compare'),
    path('csvToMongo/', views.CSVtoMongoDB.as_view(), name='csvToMongo'),
    path('users/', views.Users.as_view(), name='users'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('login/', views.Login.as_view(), name='login'),
    path('password_reset/', views.Password_Reset.as_view(), name='password_reset'),
    path('register/', views.Register.as_view(), name='register'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    url(r'^ajax_calls/search/', views.Profile.autocompleteModel),
]

newRDB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('myRDB/', include('myRDB.urls')),
    path('admin/', admin.site.urls),
]

myRDB/models.py
import datetime
import json

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date publisched')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class Orga(models.Model):
    team = models.CharField(max_length=100)
    theme_owner = models.CharField(max_length=100)


class Department(models.Model):
    department_name = models.CharField(max_length=8)


class Group(models.Model):
    group_name = models.CharField(max_length=11)


class ZI_Organisation(models.Model):
    zi_organisation_name = models.CharField(max_length=5)


class TF_Application(models.Model):
    application_name = models.CharField(max_length=100)


CHOICES = [(1, ' '), (2, 'K'), (3, 'U')]


class TF(models.Model):
    tf_name = models.CharField(max_length=100)
    tf_description = models.CharField(max_length=300)
    tf_owner_orga = models.ForeignKey(Orga, on_delete=models.CASCADE)
    tf_application = models.ForeignKey(TF_Application, on_delete=models.CASCADE)
    criticality = models.CharField(choices=CHOICES, max_length=1)
    highest_criticality_in_AF = models.CharField(choices=CHOICES, max_length=1)


class GF(models.Model):
    gf_name = models.CharField(max_length=150)
    gf_description = models.CharField(max_length=250)
    tfs = models.ManyToManyField(TF, 'owningGF')


class AF(models.Model):
    af_name = models.CharField(max_length=150)
    af_description = models.CharField(max_length=250)
    af_applied = models.DateTimeField()
    af_valid_from = models.DateTimeField()
    af_valid_till = models.DateTimeField()
    gfs = models.ManyToManyField(GF, 'owningAF')


class Role(models.Model):
    role_name = models.CharField(max_length=150)
    role_description = models.CharField(max_length=250)
    afs = models.ManyToManyField(AF, 'owningRole')


class CustomAccountManager(BaseUserManager):
    def create_user(self, identity, password):
        user = self.model(identity=identity, password=password)
        user.set_password(password)
        user.is_staff = False
        user.is_superuser = False
        user.save(using=self.db)
        return user

    def create_superuser(self, identity, password):
        user = self.create_user(identity=identity, password=password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self.db)

    def get_by_natural_key(self, identity_):
        case_insensitive_identitiy_field = '{}__iexact'.format(self.model.USERNAME_FIELD)
        print(identity_)
        return self.get(**{case_insensitive_identitiy_field: identity_})


class User(AbstractUser):
    identity = models.CharField(max_length=7, unique=True)
    name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    deleted = models.BooleanField(default=False)
    orga_id = models.ForeignKey(Orga, on_delete=models.CASCADE)
    department_id = models.ForeignKey(Department, on_delete=models.CASCADE)
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE)
    zi_organisation_id = models.ForeignKey(ZI_Organisation, on_delete=models.CASCADE)
    roles = models.ManyToManyField(Role)
    direct_connect_afs = models.ManyToManyField(AF, 'afOwningUser')
    direct_connect_gfs = models.ManyToManyField(GF, 'gfOwningUser')
    direct_connect_tfs = models.ManyToManyField(TF, 'tfOwningUser')
    is_staff = models.BooleanField(default=False)
    password = models.CharField(max_length=32)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'identity'

    objects = CustomAccountManager()

    def natural_key(self):
        return self.identity

    def get_short_name(self):
        return self.identity

    def __str__(self):
        return self.identity

    def retrieve_related_rights(self, user, roles, afs, compareUser):
        tfList = []
        gfList = []
        afList = []
        gf_count = 0
        for af in afs:
            gfs = GF.objects.filter(owningAF__id=af.id)
            gf_count += gfs.count()
            for gf in gfs:
                tfs = TF.objects.filter(owningGF__id=gf.id)
                for tf in tfs:
                    # print(tf.tf_name)
                    tfList.append(tf)
                    gfList.append(gf)
                    afList.append(af)

        data = zip(tfList, gfList, afList)
        tf_count = len(tfList)
        try:
            self.prepareJSONdata(self, user.identity, tfList, gfList, afList, compareUser)
        except(IOError):
            print("error while prparing json for graph")

        return data, gf_count, tf_count

    def prepareJSONdata(self, identity, tfList, gfList, afList, compareUser):
        scatterData = []
        scatterIndex = 0

        zippedData = zip(afList, gfList, tfList)
        jsonDict = {}
        jsonDict["name"] = identity
        jsonDict["children"] = []

        for line in zippedData:
            scatterIndex += 1
            if line[0].af_applied != None:
                af_applied = line[0].af_applied.isoformat();
            else:
                af_applied = ""
            scatterData.append({"name": line[2].tf_name, "index": scatterIndex, "af_applied": af_applied})
            inGF = False
            inAF = False
            # print(line)
            for afDict in jsonDict["children"]:
                if line[0].af_name in afDict.values():
                    inAF = True
                    for gfDict in afDict["children"]:
                        if line[1].gf_name in gfDict.values():
                            inGF = True
                            break
                        else:
                            inGF = False
                    break
                else:
                    inAF = False

            if inAF:
                if inGF:
                    # print("af und gf existieren")
                    gfDict["children"].append({"name": line[2].tf_name, "size": 3000})
                else:
                    # print("gf existiert nicht")
                    afDict["children"].append(
                        {"name": line[1].gf_name, "children": [{"name": line[2].tf_name, "size": 3000}]})
            else:
                # print("af existiert nicht")
                jsonDict["children"].append(
                    {"name": line[0].af_name,
                     "children": [{"name": line[1].gf_name, "children": [{"name": line[2].tf_name, "size": 3000}]}]})

        if compareUser:
            path = 'myRDB/static/myRDB/data/compareGraphData.json'
        else:
            path = 'myRDB/static/myRDB/data/graphData.json'
        with open(path, 'w') as outfile:
            json.dump(jsonDict, outfile, indent=2)

        scatterData.sort(key=lambda r: r["af_applied"])
        with open('myRDB/static/myRDB/data/scatterGraphData.json', 'w') as outfile:
            json.dump(scatterData, outfile, indent=2)

myRDB/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('identity',)

    # Validation von xvnummer abgeschaltet da dieses bei passwortvalidierung mit dabei
    def clean_identity(self):
        identity = self.cleaned_data['identity']
        try:
            user = User.objects.exclude(pk=self.instance.pk).get(identity=identity)
            self.errors['identity'] = self.error_class()
        except User.DoesNotExist:
            pass
        return identity

    def save(self, commit=True):
        user = None
        identity = self.cleaned_data['identity']
        identity_upper = identity.upper()

        print(identity, identity_upper)
        try:
            user = User.objects.get(identity=identity)
            print("User: ", user.__str__(), " mit Identity_lower existiert")
            if user.password == "":
                print("User mit Identity_lower existiert - password is leer -> pw wird gesafet")
                user.set_password(self.cleaned_data['password1'])
                user.save()
            else:
                print("User mit Identity_lower existiert und hat pw!")
                forms.ValidationError("User mit Identity_lower existiert und hat pw!")
                return user
                # messages.info(HttpRequest(),"User exists and has a Password")
        except(KeyError, User.DoesNotExist):
            try:
                user = User.objects.get(identity=identity_upper)
                print("User: ", user.__str__(), " mit Identity_upper existiert")
                if user.password == "":
                    print("User mit Identity_upper existiert - password is leer -> pw wird gesafet")
                    user.set_password(self.cleaned_data['password1'])
                    user.save()
                else:
                    forms.ValidationError("User mit Identity_upper existiert und hat pw!")
                    print("User mit Identity_upper existiert und hat pw!")
                return user
                # messages.info(HttpRequest(),"User exists and has a Password")
            except(KeyError, User.DoesNotExist):
                print("User existiert nicht - wird neu angelegt")
                user = super(CustomUserCreationForm, self).save(commit=False)
                user.set_password(self.cleaned_data['password1'])

                if commit:
                    user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('identity',)
        error_css_class = 'error'


class SomeForm(forms.Form):
    start_import = forms.FileInput()

myRDB/templates/myRDB/base.html
<!DOCTYPE html>
<meta charset="UTF-8">

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {#<script src="{% static 'myRDB/js/jquery-3.3.1.slim.min.js' %}"></script>#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
            type="text/javascript"></script>

    <script src="{% static 'myRDB/js/popper.min.js' %}"></script>
    <script src="{% static 'myRDB/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'myRDB/js/d3.v4.min.js' %}"></script>

    <title>{% block title %}MyRDB{% endblock %}</title>


    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css"
          media="all">
    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/circle_packing/circlePacking.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/scatter_plot/scatterPlot_fromJSON.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myRDB/css/style.css' %}">


</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'myRDB:index' %}">MyRDB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav navbar-left">
            {% if user.is_authenticated %}
            <li><a class="nav-item nav-link" href="{% url 'myRDB:profile' %}">Profile</a></li>
            <li><a class="nav-item nav-link" href="{% url 'myRDB:csvToMongo' %}">CSVintoMongoDB</a></li>
            <li><a class="nav-item nav-link" href="{% url 'myRDB:users' %}">Users</a></li>
            {% endif %}
        </ul>

    </div>
    <ul class="nav navbar-right navbar-nav">
        {% if user.is_authenticated %}
        <li><p>Youre logged in</p></li>
        <li><a class="nav-item nav-link active" href="{% url 'myRDB:logout' %}">Logout<span
                class="sr-only">(current)</span></a></li>
        {% else %}
        <li><p>Youre not logged in</p></li>
        <li><a class="nav-item nav-link active" href="{% url 'myRDB:login' %}">Login<span
                class="sr-only">(current)</span></a></li>
        {% endif %}

    </ul>
</nav>


<div class="content container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

myRDB/templates/myRDB/compare.html
{% extends 'myRDB/base.html' %}
{% block content %}
<div class="row top-buffer">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <img class="card-img-top" src="/../../static/myRDB/images/default_profile.png"
                             alt="Profile Picture">
                    </div>
                    <div class="col-9">
                        <h5 class="card-title">{{ user.identity }}</h5>
                        <p class="card-text">{{ user.name }}</p>
                        <p class="card-text">{{ user.first_name }}</p>
                        <p class="card-text">{{ user.departement_id }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-sm">
                        <p class="card-text">User:...</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">Rollen: {{ role_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">AF: {{ af_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">GF: {{ gf_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">TF: {{ tf_count }}</p>
                    </div>
                </div>
            </div>
            <div class="card-body">
                {#{% if viewMode.one %}#}
                {% include 'myRDB/circlePackingTemplate.html' %}
                {#{% else %}#}

                {% include 'myRDB/compareProfileTableTemplate.html' %}
                {#{% endif %}#}
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <img class="card-img-top" src="/../../static/myRDB/images/default_profile.png"
                             alt="Profile Picture">
                    </div>
                    <div class="col-9">
                        <h5 class="card-title">{{ compareUser.identity }}</h5>
                        <p class="card-text">{{ compareUser.name }}</p>
                        <p class="card-text">{{ compareUser.first_name }}</p>
                        <p class="card-text">{{ compareUser.departement_id }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-sm">
                        <p class="card-text">User:...</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">Rollen: {{ comp_role_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">AF: {{ comp_af_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">GF: {{ comp_gf_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">TF: {{ comp_tf_count }}</p>
                    </div>
                </div>
            </div>
            <div class="card-body">
                {#{% if viewMode2.two2 %}#}
                {% include 'myRDB/compareCirclePackingTemplate.html' %}

                {#{% else %}#}
                {% include 'myRDB/compareTableTemplate.html' %}
                {#{% endif %}#}
            </div>
        </div>
    </div>
</div>
<div class="row-fluid top-buffer">
    {# hier umschalt button auf tabellarische/visuelle ansicht #}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-2">
                    <label for="viewMode">Ansicht: </label>
                </div>
                <div class="col-3">
                    <select id="viewMode" class="form-control" onchange="location.reload()">
                        <option id="one" itemid="one" class="one">Visuelle Ansicht</option>
                        <option id="two" itemid="two" class="two">Tabellarische Ansicht</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row top-buffer">
    <div class="col">
        <div class="card">
            <div class="card-body">
                {# Hier die Trash-Drop-Fläche realisieren #}
                {% include 'myRDB/trashTemplate.html' %}
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {# Hier die Übertragenen-liste realisieren #}
            </div>
            <div class="card-footer">
                <p class="card-text"> Übertragene Rechte werden hier angezeigt</p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="row-fluid">
            <div class="card">
                <div class="card-body">
                    {# Hier die legende realisieren #}
                </div>
            </div>
        </div>
        <div class="row-fluid top-buffer">
            <div class="card">
                <div class="card-body">
                    {# Hier die verschiedenen Buttons realisieren #}
                    <div class="row">
                        <div class="col">
                            <button type="button" class="btn btn-light">Rechte Beantragen</button>
                        </div>
                    </div>
                    <div class="row top-buffer">
                        <div class="col">
                            <button type="button" class="btn btn-light">Löschung beantragen</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

myRDB/templates/myRDB/compareCirclePackingTemplate.html
{% load static %}
{# Hier die Circle-Packing-Visualisierung #}
<svg id="compareCirclePackingSVG" width="480" height="480"></svg>
<script src="{% static 'myRDB/js/circle_packing/compareCirclePacking.js' %}"></script>

myRDB/templates/myRDB/compareTableTemplate.html
<div class="table-responsive">
    <table class="table table-hover table-bordered">
        <tr>
            <th scope="col">TF</th>
            <th scope="col">GF</th>
            <th scope="col">AF</th>
            <th scope="col">Rolle</th>
        </tr>
        {% for row in compareUser_table_data %}
        <tr>
            <td>{{ row.0.tf_name }}</td>
            <td>{{ row.1.gf_name }}</td>
            <td>{{ row.2.af_name }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% if is_paginated %}
<ul class="pagination">
    {% if compareUser_table_data.has_previous %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.number }}&compare_page={{ compareUser_table_data.previous_page_number }}">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in compareUser_table_data.paginator.page_range %}
    {% if compareUser_table_data.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.number }}&compare_page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if compareUser_table_data.has_next %}
    <li>
        <a href="?userSearch={{ compareUser.identity }}&page={{ page_obj.number }}&compare_page={{ compareUser_table_data.next_page_number }}">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

myRDB/templates/myRDB/csvToMongo.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>hier wird aus csv mongo</h1>
<form action="?start_import" method="post">
    {% csrf_token %}
    <label for="start_import">start your csv-import: </label>
    <input id="start_import" type="file" name="start_import">
    <input type="submit" value="start import">
</form>
{# TODO: Assynchron & ProgressBar #}
{% endblock %}

myRDB/templates/myRDB/detail.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myRDB:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock %}

myRDB/templates/myRDB/index.html
{% extends 'myRDB/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>Wilkommen in der RechteDB</h1>
{% if user.is_authenticated %}
Hi {{user.identity}} !
<p><a href="{% url 'myRDB:logout' %}">logout</a></p>
{% else %}
<p>You are not logged in!</p>
<a href="{% url 'myRDB:login' %}">login</a>
<a href="{% url 'myRDB:register' %}">sign up</a>
{% endif %}

{% endblock %}

myRDB/templates/myRDB/navbar.html
{% extends 'myRDB/base.html' %}
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="nav navbar-nav navbar-left">
            {% if user.is_authenticated %}
            <li><a class="nav-item nav-link" href="{% url 'myRDB:profile' %}">Profile</a></li>
            <li><a class="nav-item nav-link" href="{% url 'myRDB:csvToMongo' %}">CSVintoMongoDB</a></li>
            <li><a class="nav-item nav-link disabled" href="#">Disabled</a></li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><p>Youre logged in</p></li>
            <li><a class="nav-item nav-link active" href="{% url 'myRDB:logout' %}">Logout<span class="sr-only">(current)</span></a>
            </li>
            {% else %}
            <li><p>Youre not logged in</p></li>
            <li><a class="nav-item nav-link active" href="{% url 'myRDB:login' %}">Login<span
                    class="sr-only">(current)</span></a></li>
            {% endif %}

        </ul>
    </div>
</nav>

{% endblock %}

myRDB/templates/myRDB/profile.html
{% extends 'myRDB/base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-2">
                        <img class="card-img-top card-image" src="/../../static/myRDB/images/default_profile.png"
                             alt="Profile Picture">
                    </div>
                    <div class="col-9">
                        <h5 class="card-title">{{ user.identity }}</h5>
                        <p class="card-text">{{ user.name }}</p>
                        <p class="card-text">{{ user.first_name }}</p>
                        <p class="card-text">{{ user.departement_id }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <p class="card-text">User:...</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">Roles: {{ role_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">AF: {{ af_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">GF: {{ gf_count }}</p>
                    </div>
                    <div class="col-sm">
                        <p class="card-text">TF: {{ tf_count }}</p>
                    </div>
                    <div class="col-4 input-group mb-3">
                        <form id=”search” method=”POST” action="{% url 'myRDB:compare' %}">
                            {% csrf_token %}
                            <input type=”text” class=”form-control” id=”txtSearch” name='userSearch'
                                   placeholder="compare to...">
                            <button type="button" class="btn btn-light btn-outline-secondary">Compare</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row top-buffer">
                {# hier umschalt button auf tabellarische/visuelle ansicht #}
                <div class="col-1">
                    <label for="viewMode">Ansicht: </label>
                </div>
                <div class="col-3">
                    <form method="post">
                        <select id="viewMode" class="form-control" onchange="location.reload()">
                            <option value="one" id="one" itemid="one" class="one">Visuelle Ansicht</option>
                            <option value="two" id="two" itemid="two" class="two">Tabellarische Ansicht</option>
                        </select>
                    </form>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row top-buffer">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            {#{% if viewMode.one %}#}
                            {% include 'myRDB/circlePackingTemplate.html' %}
                            {#{% else %}#}
                            {% include 'myRDB/profileTableTemplate.html' %}

                            {#{% endif %}#}
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="row">
                        <div class="col">
                            {% include 'myRDB/scatterPlotTemplate.html' %}
                        </div>
                    </div>
                    <div class="row top-buffer">
                        <div class="col">
                            {% include 'myRDB/trashTemplate.html' %}
                        </div>
                        <div class="col">
                            <div class="card">
                                <div class="card-body">
                                    {# Hier die verschiedenen Buttons realisieren #}
                                    <div class="row">
                                        <div class="col">
                                            <button type="button" class="btn btn-light">Logdatei anzeigen</button>
                                        </div>
                                    </div>
                                    <div class="row top-buffer">
                                        <div class="col">
                                            <button type="button" class="btn btn-light">Berechtigungsanalyse</button>
                                        </div>
                                    </div>
                                    <div class="row top-buffer">
                                        <div class="col">
                                            <button type="button" class="btn btn-light">Rechte Beantragen</button>
                                        </div>
                                    </div>
                                    <div class="row top-buffer">
                                        <div class="col">
                                            <button type="button" class="btn btn-light">Löschung beantragen</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<script>
        $(document).ready(function(){
            $("#txtSearch").autocomplete({
                source: "/ajax_calls/search/",
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
              });

        });



</script>

{% endblock %}

myRDB/templates/myRDB/results.html
{% extends 'myRDB/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'myRDB:detail' question.id %}">Vote again?</a>
{% endblock %}